jbot:  
  # Publish all joint states -----------------------------------  
  joint_state_controller:  
    type: joint_state_controller/JointStateController  
    publish_rate: 50
    
  # Position Controllers ---------------------------------------  
  joint1_position_controller:  
    type: effort_controllers/JointPositionController  
    joint:joint_wheel_1
    pid: {p: 100.0, i: 0.01, d: 10.0}  
  joint2_position_controller:  
    type: effort_controllers/JointPositionController  
    joint:joint_wheel_2  
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint3_position_controller:  
    type: effort_controllers/JointPositionController  
    joint:joint_wheel_3
    pid: {p: 100.0, i: 0.01, d: 10.0}  
  joint4_position_controller:  
    type: effort_controllers/JointPositionController  
    joint:joint_wheel_4  
    pid: {p: 100.0, i: 0.01, d: 10.0} 
