controller_frequency: 3.0
recovery_behavior_enabled: true
clearing_rotation_allowed: true

TrajectoryPlannerROS:
  max_vel_x: 0.18
  min_vel_x: 0.08
  max_vel_y: 0.18   # zero for a differential drive robot
  min_vel_y: 0.08
  max_vel_theta: 0.26
  min_vel_theta: 0.15
  min_in_place_vel_theta: 0.24
  min_in_place_rotational_vel: 0.22
  escape_vel: -0.10
  acc_lim_x: 2.0
  acc_lim_y: 2.0   # zero for a differential drive robot
  acc_lim_theta: 2.0

  holonomic_robot: true
  yaw_goal_tolerance: 0.55 # about 28 degrees
  xy_goal_tolerance: 0.25 # 15 cm
  gdist_scale: 0.4  # goal
  pdist_scale: 0.8  # path, global

  heading_lookahead: 2
  heading_scoring: false
  heading_scoring_timestep: 0.1
  meter_scoring: true
  oscillation_reset_dist: 0.5
  occdist_scale: 0.05
  publish_cost_grid_pc: false

  sim_time: 1.8
  sim_granularity: 0.18
  angular_sim_granularity: 0.08  #0.025
  vx_samples: 6
  vy_samples: 6   # zero for a differential drive robot
  vtheta_samples: 20
  dwa: true
  simple_attractor: false

