controller_frequency: 3.0
recovery_behavior_enabled: true
clearing_rotation_allowed: true

TrajectoryPlannerROS:
  max_vel_x: 0.20
  min_vel_x: 0.10
  max_vel_y: 0   # zero for a differential drive robot
  min_vel_y: 0
  max_vel_theta: 0.22
  min_vel_theta: 0.12
  min_in_place_vel_theta: 0.11
  min_in_place_rotational_vel: 0.13
  escape_vel: -0.10
  acc_lim_x: 0.2
  acc_lim_y: 0   # zero for a differential drive robot
  acc_lim_theta: 0.2

  holonomic_robot: false
  yaw_goal_tolerance: 0.2 # about 12*2 degrees
  xy_goal_tolerance: 0.15 # 15 cm
  gdist_scale: 0.4
  pdist_scale: 0.6

  heading_lookahead: 1.5
  heading_scoring: false
  heading_scoring_timestep: 0.1
  meter_scoring: true
  oscillation_reset_dist: 0.05
  occdist_scale: 0.05
  publish_cost_grid_pc: false

  sim_time: 1.4
  sim_granularity: 0.08
  angular_sim_granularity: 0.025
  vx_samples: 8
  vy_samples: 0   # zero for a differential drive robot
  vtheta_samples: 14
  dwa: true
  simple_attractor: false

  

