controller_frequency: 3.0
recovery_behavior_enabled: false
clearing_rotation_allowed: false

TrajectoryPlannerROS:
  max_vel_x: 0.25
  min_vel_x: 0.12
  max_vel_y: 0   # zero for a differential drive robot
  min_vel_y: 0
  max_vel_theta: 0.51
  min_vel_theta: -0.51
  min_in_place_vel_theta: 0.26
  escape_vel: -0.10
  acc_lim_x: 2.5
  acc_lim_y: 2.5   # zero for a differential drive robot
  acc_lim_theta: 3.2

  holonomic_robot: false
  yaw_goal_tolerance: 0.12 # about 10 degrees
  xy_goal_tolerance: 0.12 # 12 cm
  latch_xy_goal_tolerance: false
  gdist_scale: 0.5
  pdist_scale: 0.8

  heading_lookahead: 0.325
  heading_scoring: false
  heading_scoring_timestep: 0.8
  meter_scoring: true
  oscillation_reset_dist: 0.05
  occdist_scale: 0.1
  publish_cost_grid_pc: false
  prune_plan: true

  sim_time: 1.0
  sim_granularity: 0.025
  angular_sim_granularity: 0.025
  vx_samples: 8
  vy_samples: 0   # zero for a differential drive robot
  vtheta_samples: 20
  dwa: true
  simple_attractor: false

  

